version: '3.7'
services:
  tracing:
    image: jaegertracing/all-in-one:1.8.2
    ports:
      - '5775:5775'
      - '5778:5778'
      - '6831:6831'
      - '6832:6832'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
    environment:
      COLLECTOR_ZIPKIN_PORT: '9411'
  order-service:
    build: .
    depends_on:
      - tracing
    restart: always
    environment:
      NODE_ENV: 'development'
      ENABLE_TRACING: 'true'
    ports:
      - '4000:4000'
    init: true
